sudo: false
language: node_js
node_js:
  - 0.10
  - 0.12
  - 4.0
  - 4.1
  - 4.2
  - 4.3
  - 5.6
matrix:
    allow_failures:
        - node_js: 4.0
        - node_js: 4.1
        - node_js: 4.2
        - node_js: 4.3
        - node_js: 5.6